# How is it useful to decompose an image into it's bit planes?

By decomposing an image into bit planes, we can access more details of that image which cannot be accessed otherwise. One particular example would be image steganography, where we hide data in the lowest bit plane, without any visible change in the overall image. 

# Find all the bit planes of hte following image - 

In [1]:
import cv2 
import matplotlib.pyplot as plt 

In [29]:
def bitPlaneSlicing(r, bit_plane):
    dec = np.binary_repr(r, width = 4)
    return int(dec[4-bit_plane])

bitPlaneSlicingVec = np.vectorize(bitPlaneSlicing)

In [9]:
dollar = cv2.imread("dollar.tif",0)

In [10]:
dollar.dtype

dtype('uint8')

In [7]:
img.shape

(500, 1192)

In [12]:
img = np.array([[0, 3, 7, 8],
           [1, 1, 2, 2],
          [3, 14, 15, 13],
          [4,6,9,11]], dtype='uint8'
          )

In [15]:
bitPlaneSlicingVec(img, bit_plane=1)

array([[0, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1]])

In [16]:
bitPlaneSlicingVec(img, bit_plane=2)

array([[0, 1, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 1]])

In [17]:
bitPlaneSlicingVec(img, bit_plane=3)

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 0]])

In [18]:
bitPlaneSlicingVec(img, bit_plane=4)

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 1, 1]])